pipeline {
    agent any
    tools {
        maven 'maven'
        }
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'master',
                credentialsId: '0122853b-cb76-47f5-bb46-cc5a3c7649fc',
                url: 'https://github.com/jatinkumar0/junit.git'
                }
        }
        stage ('Compile') {
            steps {
                sh 'mvn compile'
                }
            }  
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage ('Create war file') {
                steps {
                    sh 'jar -cf target/dependency/webapp-runner.jar target/my-app-1.0-SNAPSHOT.jar'
                    }
                }
          
         stage ('Deploy War File') {
                 steps {
                   sh "cp target/my-app-1.0-SNAPSHOT.jar /home/ec2-user/apache-tomcat-8.5.61/webapps"
                    }
                }
    }
}
